// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Deployment struct {
	ID         string         `db:"id" json:"id"`
	FunctionID string         `db:"function_id" json:"function_id"`
	Provider   string         `db:"provider" json:"provider"`
	ResourceID string         `db:"resource_id" json:"resource_id"`
	Status     string         `db:"status" json:"status"`
	Replicas   int64          `db:"replicas" json:"replicas"`
	ImageTag   sql.NullString `db:"image_tag" json:"image_tag"`
	CreatedAt  sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Function struct {
	ID             string         `db:"id" json:"id"`
	Name           string         `db:"name" json:"name"`
	Description    sql.NullString `db:"description" json:"description"`
	CodePath       string         `db:"code_path" json:"code_path"`
	Runtime        string         `db:"runtime" json:"runtime"`
	Handler        string         `db:"handler" json:"handler"`
	TimeoutSeconds int64          `db:"timeout_seconds" json:"timeout_seconds"`
	MemoryMb       int64          `db:"memory_mb" json:"memory_mb"`
	EnvVars        sql.NullString `db:"env_vars" json:"env_vars"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Invocation struct {
	ID                string         `db:"id" json:"id"`
	FunctionID        string         `db:"function_id" json:"function_id"`
	DeploymentID      sql.NullString `db:"deployment_id" json:"deployment_id"`
	Status            string         `db:"status" json:"status"`
	DurationMs        sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	MemoryUsedMb      sql.NullInt64  `db:"memory_used_mb" json:"memory_used_mb"`
	ResponseSizeBytes sql.NullInt64  `db:"response_size_bytes" json:"response_size_bytes"`
	Logs              sql.NullString `db:"logs" json:"logs"`
	Error             sql.NullString `db:"error" json:"error"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	CompletedAt       sql.NullTime   `db:"completed_at" json:"completed_at"`
}
