// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type MemoriesFt struct {
	UserID   string `json:"user_id"`
	SourceID string `json:"source_id"`
	Memory   string `json:"memory"`
}

type Memory struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	SourceID    string         `json:"source_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CreatedDate sql.NullString `json:"created_date"`
	Memory      string         `json:"memory"`
}

type Source struct {
	ID          string         `json:"id"`
	UserID      int64          `json:"user_id"`
	Description sql.NullString `json:"description"`
	Protected   sql.NullBool   `json:"protected"`
}

type User struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CreatedDate sql.NullString `json:"created_date"`
}
