// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Host struct {
	Address   string `json:"address"`
	NetworkID int64  `json:"network_id"`
	Comments  string `json:"comments"`
}

type HostAttribute struct {
	Address string `json:"address"`
	Key     string `json:"key"`
	Value   string `json:"value"`
}

type HostPort struct {
	Address  string `json:"address"`
	Port     int64  `json:"port"`
	Protocol string `json:"protocol"`
	Comments string `json:"comments"`
}

type HostPortAttribute struct {
	Address  string `json:"address"`
	Port     int64  `json:"port"`
	Protocol string `json:"protocol"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type Network struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Cidr     int64  `json:"cidr"`
	Comments string `json:"comments"`
}

type NetworkAttribute struct {
	NetworkID int64  `json:"network_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
}

type NetworkScan struct {
	ID         int64 `json:"id"`
	NetworkID  int64 `json:"network_id"`
	StartedAt  int64 `json:"started_at"`
	FinishedAt int64 `json:"finished_at"`
	HostsFound int64 `json:"hosts_found"`
	PortsFound int64 `json:"ports_found"`
}
