---

name: Build nomad-deployer app

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.**" ]
    paths:
    - ".github/workflows/build-nomad-deployer.yml"
    - "go.*"
    - "pkg/**"
    - "nomad-deployer/**"
  pull_request:
    branches: [ "main" ]
    paths:
    - ".github/workflows/build-nomad-deployer.yml"
    - "go.*"
    - "pkg/**"
    - "nomad-deployer/**"

jobs:
  build-docker-image:
    uses: pirogoeth/workflows/.github/workflows/docker-generic.yml@main
    with:
      output-registry: "ghcr.io"
      output-repository-path: "${{ github.repository }}/nomad-deployer"
      dockerfile-path: "./nomad-deployer/Dockerfile"
    permissions:
      contents: read
      packages: write
